# Generated by Django 4.2.20 on 2025-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'English')], default=('ES', 'Español'), max_length=20),
        ),
    ]
