# Generated by Django 5.1.7 on 2025-03-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_user_message_quiz_rating_administrator_participation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persistence.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persistence.user')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
