# Generated by Django 5.1.7 on 2025-04-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_message_receiver_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
