# Generated by Django 4.2.20 on 2025-04-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_alter_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(help_text='Usuario que fue reportado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(help_text='Usuario que ha hecho el reporte', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportresolution',
            name='date_resolved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reportresolution',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Administrador que resolvió el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.TextField(help_text='Descripción del motivo del reporte'),
        ),
        migrations.AlterField(
            model_name='reportresolution',
            name='action',
            field=models.CharField(choices=[('NoAction', 'Ninguna acción'), ('Warning', 'Aviso'), ('Ban', 'Bloqueo')], help_text='Acción tomada como resultado del reporte', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportresolution',
            name='message',
            field=models.TextField(help_text='Comentario adicional del administrador'),
        ),
        migrations.AlterField(
            model_name='reportresolution',
            name='report',
            field=models.OneToOneField(help_text='Reporte al que se aplica esta resolución', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='persistence.report'),
        ),
    ]
