# Generated by Django 4.2.20 on 2025-04-30 23:43

from django.db import migrations, models
import persistence.models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_remove_report_user_report_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=persistence.models.event_image_path),
        ),
    ]
