# Generated by Django 4.2.20 on 2025-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
