# Generated by Django 4.2.20 on 2025-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ES', 'Español'), ('CAT', 'Català')], default='ES', max_length=20),
        ),
    ]
