# Generated by Django 4.2.20 on 2025-05-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_user_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.TextField(help_text='Comentario del usuario que se ha reportado', null=True),
        ),
    ]
