# Generated by Django 4.2.20 on 2025-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ES', 'Español'), ('CAT', 'Català')], default=('ES', 'Español'), max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank_event',
            field=models.CharField(choices=[('Unranked', 'Sin Rango'), ('Bronze', 'Bronce'), ('Silver', 'Plata'), ('Gold', 'Oro'), ('RamonLlull', 'Ramon Llull')], default='Unranked', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank_quiz',
            field=models.CharField(choices=[('Bad', 'Malo'), ('Mediocre', 'Mediocre'), ('KindaFun', 'Entretenido'), ('Fun', 'Divertido'), ('Awesome', 'Increíble')], default='Bad', max_length=20),
        ),
    ]
