# Generated by Django 4.2.20 on 2025-05-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_report_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ES', 'Español'), ('EN', 'English')], max_length=10)),
                ('text', models.TextField(help_text='Pregunta en sí en el idioma correspondiente')),
                ('options', models.JSONField(help_text='lista de opciones disponibles en el idioma correspondiente')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_es',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AddField(
            model_name='questiontranslation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='persistence.question'),
        ),
        migrations.AlterUniqueTogether(
            name='questiontranslation',
            unique_together={('question', 'language')},
        ),
    ]
