# Generated by Django 4.2.20 on 2025-03-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_alter_user_language_alter_user_rank_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcalendar',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persistence.event'),
        ),
    ]
