# Generated by Django 4.2.20 on 2025-03-27 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0007_alter_personalcalendar_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalcalendar',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='personalcalendar',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='personalcalendar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_calendar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persistence.event')),
                ('personal_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='persistence.personalcalendar')),
            ],
            options={
                'unique_together': {('personal_calendar', 'event')},
            },
        ),
    ]
