# Generated by Django 4.2.20 on 2025-05-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0007_questiontranslation_remove_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_es',
            field=models.TextField(null=True),
        ),
    ]
