# Generated by Django 4.2.20 on 2025-05-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0008_alter_question_question_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_event_points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_quiz_points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
