# Generated by Django 4.2.20 on 2025-03-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0008_rename_added_at_personalcalendar_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcalendar',
            name='event',
        ),
    ]
