# Generated by Django 4.2.20 on 2025-03-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0009_remove_personalcalendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='persistence.event'),
        ),
    ]
