# Generated by Django 4.2.20 on 2025-05-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0009_user_total_event_points_user_total_quiz_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events_assisted',
            field=models.ManyToManyField(blank=True, related_name='events_assisted', to='persistence.event'),
        ),
    ]
