# Generated by Django 4.2.20 on 2025-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0010_rating_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank_quiz',
            field=models.CharField(choices=[('Unranked', 'Sin Rango'), ('Bronze', 'Bronce'), ('Silver', 'Plata'), ('Gold', 'Oro'), ('RamonLlull', 'Ramon Llull')], default='Unranked', max_length=20),
        ),
    ]
