# Generated by Django 4.2.20 on 2025-05-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0011_alter_user_rank_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points_to_next_quiz_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points_to_next_rank_event',
        ),
    ]
