# Generated by Django 4.2.20 on 2025-05-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0012_remove_user_points_to_next_quiz_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_event_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_quiz_points',
        ),
    ]
