# Generated by Django 4.2.20 on 2025-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0012_rating_user_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank_quiz',
            field=models.CharField(choices=[('Bad', 'Malo'), ('Mediocre', 'Mediocre'), ('KindaFun', 'Entretenido'), ('Fun', 'Divertido'), ('Awesome', 'Increíble')], default='Bad', max_length=20),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
