# Generated by Django 4.2.20 on 2025-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0013_remove_user_current_event_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'English')], default='ES', max_length=20),
        ),
    ]
