# Generated by Django 4.2.20 on 2025-03-30 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0013_alter_rating_unique_together_rating_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user_email',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
