# Generated by Django 4.2.20 on 2025-05-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0014_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
